### ISSUE TITLE
Game Hunter

### ISSUE THREAD

**Issue by kwhat** [gpoteau/XLinkUSB#1]
Do you know if this will work with a "Game Hunter"?  How can I tell the difference between card types?

**Comment by gpoteau** [comment]
It's work only with the xplorer card. I think the "Game Hunter" it's a clone of the ACTION REPLAY, but I not sure, but if it's the case, you can use "CommLinkUSB"
Some cards use a proprietary connection, some other use the PRINTER port of the PC. As a exemple, "PRO ACTION REPLAY" use a proprietary port, "XPLORER / XPLODER" use the printer port, "GAME SHARK PRO" use the printer port but not in the same way as "XPLORER/ XPLODER"
